### ISSUE TITLE
Feature Request: Configurable redirect route after photo is updated

### ISSUE THREAD

**Issue by Jonnx** [RhysLees/jetstream-team-profile-photo#5]
There is a use case I just ran into, where I want to re-structure my jetstream application to move all settings including the built-in team ones under a `/settings` prefix and may want to "move" the routes to `settings.teams...`. When doing this, a error is thrown by the update action due to the following line:

```
return redirect()->route('teams.show', $this->team);
``` 

Proposed Solution:
- create an config file that can be exported to the config folder
- file contains a setting for "post_photo_upload_redirect_route"
- setting should default to `teams.show` but should be overridable

Potential Issues:
- not sure how we could make route parameters configurable as well if they need more than just the team

**Comment by Jonnx** [comment]
love the package by the way. exactly what i needed and works perfectly on laravel/vapo

**Comment by RhysLees** [comment]
> * rable as well if

Thanks, glad it's working well for you!

I'll take a look into making the route configurable.

**Comment by RhysLees** [comment]
You can now specify the redirect route name in https://github.com/RhysLees/jetstream-team-profile-photo/releases/tag/2.1.0

For route params this is included in https://github.com/RhysLees/jetstream-team-profile-photo/releases/tag/2.1.1

See the updated readme for instructions 😀

**Comment by Jonnx** [comment]
this is awesome! just saw the updated version coming in with a composer update
